// Constant for mapping game mode id to game mode name
export const gameModes = [
  "unknown",
  "all_pick",
  "captains_mode",
  "random_draft",
  "single_draft",
  "all_random",
  "intro",
  "diretide",
  "reverse_captains_mode",
  "greeviling",
  "tutorial",
  "mid_only",
  "least_played",
  "limited_heroes",
  "compendium_matchmaking",
  "custom",
  "captains_draft",
  "balanced_draft",
  "ability_draft",
  "event",
  "all_random_death_match",
  "1v1_mid",
  "all_draft",
  "turbo",
  "mutation",
];
