// File for naming common hero name/ nicknames to Opendota localized names

// Object where key is the official name, and the value is potential aliases
const heroAliases = {
  Abaddon: [],
  Alchemist: ["alch"],
  "Ancient Apparition": ["aa"],
  "Anti-Mage": ["am", "antimage"],
  "Arc Warden": ["aw"],
  Axe: [],
  Bane: [],
  Batrider: ["bat"],
  Beastmaster: [],
  Bloodseeker: ["bs"],
  "Bounty Hunter": ["bh", "bounty"],
  "Brew Master": ["brew"],
  Bristleback: ["bb", "bristle"],
  Broodmother: ["brood"],
  "Centaur Warunner": ["cw"],
  "Chaos Knight": ["ck"],
  Chen: [],
  Clinkz: [],
  Clockwerk: ["clock"],
  "Crystal Maiden": ["cm"],
  "Dark Seer": ["ds"],
  "Dark Willow": ["willow", "dw"],
  Dawnbreaker: ["dawn"],
  Dazzle: [],
  "Death Prophet": ["dp"],
  Disruptor: [],
  Doom: [],
  "Dragon Knight": ["dk"],
  "Drow Ranger": ["dr", "drow"],
  "Earth Spirit": [],
  Earthshaker: ["shaker"],
  "Elder Titan": ["et"],
  "Ember Spirit": ["ember"],
  Enchantress: [],
  Enigma: [],
  "Faceless Void": ["fv", "faceless"],
  Grimstroke: [],
  Gryocopter: ["gyro"],
  Hoodwink: ["hood"],
  Huskar: [],
  Invoker: ["voker"],
  Io: [],
  Jakiro: [],
  Juggernaut: ["jug", "jugg"],
  "Keeper of the Light": ["kotl"],
  Kunkka: [],
  "Legion Commander": ["lc"],
  Leshrac: ["lesh"],
  Lich: [],
  Lifestealer: ["ls"],
  Lina: [],
  Lion: [],
  "Lone Druid": ["ld", "garymain"],
  Luna: [],
  Lycan: [],
  Magnus: [],
  Marci: [],
  Mars: [],
  Medusa: ["dusa"],
  Meepo: [],
  Mirana: ["potm"],
  "Monkey King": ["wukong"],
  Morphling: ["morph"],
  "Naga Siren": ["naga"],
  "Nature's Prophet": ["np", "natures"],
  Necrophos: ["necro"],
  "Night Stalker": ["ns"],
  "Nyx Assassin": ["nyx"],
  "Ogre Magi": ["ogre"],
  Omniknight: ["omni"],
  Oracle: [],
  "Outworld Devourer": ["od", "outworld"],
  Pangolier: ["pango"],
  "Phantom Assassin": ["pa"],
  "Phantom Lancer": ["pl"],
  Phoenix: [],
  "Primal Beast": ["primal"],
  Puck: [],
  Pudge: [],
  Pugna: [],
  "Queen of Pain": ["qop"],
  Razor: [],
  Riki: [],
  Rubick: [],
  "Sand King": ["sk"],
  "Shadow Demon": ["sd"],
  "Shadow Fiend": ["sf"],
  "Shadow Shaman": ["shaman"],
  Silencer: [],
  "Skywrath Mage": ["skywrath", "sky"],
  Slardar: [],
  Slark: [],
  Snapfire: [],
  Sniper: [],
  Spectre: ["spec"],
  "Spirit Breaker": ["sb"],
  "Storm Spirit": ["storm"],
  Sven: [],
  Techies: [],
  "Templar Assassin": ["ta", "templar"],
  Terrorblade: ["tb"],
  Tidehunter: ["tide"],
  Timbersaw: ["timber"],
  Tinker: [],
  Tiny: [],
  "Treant Protector": ["treant"],
  "Troll Warlord": ["troll", "tw"],
  Tusk: [],
  Underlord: [],
  Undying: [],
  Ursa: [],
  "Vengeful Spirit": ["venge"],
  Venomancer: ["veno"],
  Viper: [],
  Visage: [],
  "Void Spirit": ["void"],
  Warlock: [],
  Weaver: [],
  Windranger: ["wr"],
  "Winter Wyvern": ["ww", "winter", "wyvern"],
  "Witch Doctor": ["wd", "witch"],
  "Wraith King": ["wk", "wraith"],
  Zeus: [],
};

// Create inverted object, and include the lowercase version of the hero name
// as another key
const inverse = {};
Object.entries(heroAliases).forEach(([key, values]) => {
  inverse[key.replace(/ /g, "").toLowerCase()] = key;
  values.forEach((value) => (inverse[value] = key));
});

export const heroNames = inverse;
