// File for naming common hero name/ nicknames to Opendota localized names
// Mapping from lowercase to uppercase is left there as a flag for which heroes
// exist incase they don't have aliases

export const heroNames = {
  am: "Anti-Mage",
  antimage: "Anti-Mage",
  axe: "Axe",
  bane: "Bane",
  bs: "Bloodseeker",
  bloodseeker: "Bloodseeker",
  cm: "Crystal Maiden",
  crystalmaiden: "Crystal Maiden",
  drow: "Drow Ranger",
  drowranger: "Drow Ranger",
  earthshaker: "Earthshaker",
  jug: "Juggernaut",
  jugg: "Juggernaut",
  juggernaut: "Juggernaut",
  potm: "Mirana",
  mirana: "Mirana",
  morph: "Morphling",
  morphling: "Morphling",
  sf: "Shadow Fiend",
  shadowfriend: "Shadow Fiend",
  shadowfiend: "Shadow Fiend",
  pl: "Phantom Lancer",
  lancer: "Phantom Lancer",
  phantomlancer: "Phantom Lancer",
  puck: "Puck",
  dendi: "Pudge",
  pudge: "Pudge",
  razor: "Razor",
  sk: "Sand King",
  sandking: "Sand King",
  storm: "Storm Spirit",
  stormspirit: "Storm Spirit",
  sven: "Sven",
  tiny: "Tiny",
  venge: "Vengeful Spirit",
  vengefulspirit: "Vengeful Spirit",
  wind: "Windranger",
  windranger: "Windranger",
  zuus: "Zeus",
  zeus: "Zeus",
  kunkka: "Kunkka",
  lina: "Lina",
  lion: "Lion",
  shadowshaman: "Shadow Shaman",
  slardar: "Slardar",
  tide: "Tidehunter",
  tidehunter: "Tidehunter",
  wd: "Witch Doctor",
  witchdoctor: "Witch Doctor",
  lich: "Lich",
  riki: "Riki",
  enigma: "Enigma",
  tinker: "Tinker",
  sniper: "Sniper",
  necro: "Necrophos",
  necrophos: "Necrophos",
  warlock: "Warlock",
  beast: "Beastmaster",
  beastmaster: "Beastmaster",
  qop: "Queen of Pain",
  queenofpain: "Queen of Pain",
  veno: "Venomancer",
  venomancer: "Venomancer",
  fv: "Faceless Void",
  faceless: "Faceless Void",
  facelessvoid: "Faceless Void",
  wk: "Wraith King",
  wraithking: "Wraith King",
  dp: "Death Prophet",
  deathprophet: "Death Prophet",
  pa: "Phantom Assassin",
  phantomassassin: "Phantom Assassin",
  pugna: "Pugna",
  ta: "Templar Assassin",
  templarassassin: "Templar Assassin",
  snek: "Viper",
  viper: "Viper",
  luna: "Luna",
  dk: "Dragon Knight",
  dragonknight: "Dragon Knight",
  dazzle: "Dazzle",
  clock: "Clockwerk",
  clockwork: "Clockwerk",
  clockwerk: "Clockwerk",
  lesh: "Leshrac",
  leshrac: "Leshrac",
  natures: "Nature's Prophet",
  "nature's": "Nature's Prophet",
  np: "Nature's Prophet",
  furion: "Nature's Prophet",
  naturesprophet: "Nature's Prophet",
  "nature'sprophet": "Nature's Prophet",
  ls: "Lifestealer",
  naix: "Lifestealer",
  lifestealer: "Lifestealer",
  ds: "Dark Seer",
  darkseer: "Dark Seer",
  clinkz: "Clinkz",
  omni: "Omniknight",
  omniknight: "Omniknight",
  enchantress: "Enchantress",
  huskar: "Huskar",
  ns: "Night Stalker",
  nightstalker: "Night Stalker",
  brood: "Broodmother",
  broodmother: "Broodmother",
  bounty: "Bounty Hunter",
  bh: "Bounty Hunter",
  bountyhunter: "Bounty Hunter",
  weaver: "Weaver",
  jakiro: "Jakiro",
  batrider: "Batrider",
  bat: "Batrider",
  chen: "Chen",
  spec: "Spectre",
  spectre: "Spectre",
  specter: "Spectre",
  aa: "Ancient Apparition",
  ancientapparition: "Ancient Apparition",
  doom: "Doom",
  sb: "Spirit Breaker",
  spiritbreaker: "Spirit Breaker",
  gyro: "Gryocopter",
  gyrocopter: "Gyrocopter",
  alch: "Alchemist",
  alchemist: "Alchemist",
  voker: "Invoker",
  karl: "Invoker",
  invoker: "Invoker",
  silencer: "Silencer",
  od: "Outworld Destroyer",
  outworld: "Outworld Destroyer",
  outworlddevourer: "Outworld Destroyer",
  outworlddestroyer: "Outworld Destroyer",
  lycan: "Lycan",
  brew: "Brew Master",
  brewmaster: "Brew Master",
  sd: "Shadow Demon",
  shadowdemon: "Shadow Demon",
  ld: "Lone Druid",
  lonedruid: "Lone Druid",
  ck: "Chaos Knight",
  chaosknight: "Chaos Knight",
  meepo: "Meepo",
  treant: "Treant Protector",
  treantprotector: "Treant Protector",
  ogre: "Ogre Magi",
  ogremagi: "Ogre Magi",
  undying: "Undying",
  rubick: "Rubick",
  rubik: "Rubick",
  disruptor: "Disruptor",
  nyx: "Nyx Assassin",
  nyxassassin: "Nyx Assassin",
  naga: "Naga Siren",
  nagasiren: "Naga Siren",
  kotl: "Keeper of the Light",
  keeperofthelight: "Keeper of the Light",
  io: "Io",
  visage: "Visage",
  slark: "Slark",
  dusa: "Medusa",
  medusa: "Medusa",
  troll: "Troll Warlord",
  trollwarlord: "Troll Warlord",
  cw: "Centaur Warrunner",
  centaur: "Centaur Warrunner",
  warunner: "Centaur Warrunner",
  centaurwarrunner: "Centaur Warrunner",
  magnus: "Magnus",
  timbersaw: "Timbersaw",
  timber: "Timbersaw",
  bb: "Bristleback",
  bristle: "Bristleback",
  bristleback: "Bristleback",
  tusk: "Tusk",
  sky: "Skywrath Mage",
  skywrath: "Skywrath Mage",
  skywrathmage: "Skywrath Mage",
  abaddon: "Abaddon",
  et: "Elder Titan",
  eldertitan: "Elder Titan",
  legion: "Legion Commander",
  lc: "Legion Commander",
  legioncommander: "Legion Commander",
  techies: "Techies",
  ember: "Ember Spirit",
  emberspirit: "Ember Spirit",
  earthspirit: "Earth Spirit",
  underlord: "Underlord",
  tb: "Terrorblade",
  terrorblade: "Terrorblade",
  phoenix: "Phoenix",
  oracle: "Oracle",
  winter: "Winter Wyvern",
  wyvern: "Winter Wyvern",
  winterwyvern: "Winter Wyvern",
  arc: "Arc Warden",
  arcwarden: "Arc Warden",
  mk: "Monkey King",
  monkeyking: "Monkey King",
  willow: "Dark Willow",
  darkwillow: "Dark Willow",
  pango: "Pangolier",
  pangolier: "Pangolier",
  voidspirit: "Void Spirit",
  snap: "Snapfire",
  snapfire: "Snapfire",
  mars: "Mars",
  hoodwink: "Hoodwink",
  hood: "Hoodwink",
  hw: "Hoodwink",
  dawnbreaker: "Dawnbreaker",
  dawn: "Dawnbreaker",
  db: "Dawnbreaker",
};
